fake_munro = {
    "hillnumber": "1",
    "hillname": "Ben Chonzie",
    "region": "01A",
    "parent": "",
    "classification": "Ma,M,Sim",
    "metres": "931",
    "feet": "3054",
    "gridref": "NN773308",
    "gridref10": "NN 77326 30850",
    "colgridref": "NN 5609 2772",
    "colheight": "283.4",
    "drop": "648",
    "feature": "cairn/shelter",
    "observations": "",
    "survey": "Abney level",
    "revision": "2021-07-11",
    "comments": "col height measured with Leica RX1250",
    "map50": "51 52",
    "map25": "OL47W 368W 379W",
    "xcoord": "277324",
    "ycoord": "730857",
    "latitude": "56.453851",
    "longitude": "-3.992057",
    "country": "S",
    "climbed": "",
    "tumponly": "0",
    "Ma": "1",
    "MaE": "0",
    "Hu": "1",
    "HuE": "0",
    "Tu": "1",
    "Sim": "1",
    "V5": "0",
    "M": "1",
    "MT": "0",
    "F": "0",
    "C": "0",
    "G": "0",
    "D": "0",
    "DT": "0",
    "Hew": "0",
    "N": "0",
    "Dew": "0",
    "DDew": "0",
    "HF": "0",
    "V4": "0",
    "V3": "0",
    "V2": "0",
    "V1": "0",
    "V0": "0",
    "W": "0",
    "WO": "0",
    "B": "0",
    "Sy": "0",
    "Fel": "0",
    "CoH": "0",
    "CoA": "0",
    "CoU": "0",
    "CoL": "0",
    "SIB": "0",
    "sMa": "0",
    "sHu": "0",
    "sSim": "0",
    "s5": "0",
    "s4": "0",
    "Mur": "1",
    "CT": "0",
    "GT": "0",
    "DN": "0",
    "BL": "0",
    "Bg": "0",
    "Y": "1",
    "Cm": "0",
    "T100": "0",
    "xMT": "0",
    "xC": "0",
    "xG": "0",
    "xN": "0",
    "xDT": "0",
    "O": "0",
    "Un": "0",
    "P600": "1",
    "P500": "1",
    "id": "643f0095ab5591a12a3a8c4b",
}

fake_munro_data = {
    "hillnumber": "1",
    "hillname": "Ben Chonzie",
    "region": "01A",
    "parent": "",
    "classification": "Ma,M,Sim",
    "metres": "931",
    "feet": "3054",
    "gridref": "NN773308",
    "gridref10": "NN 77326 30850",
    "colgridref": "NN 5609 2772",
    "colheight": "283.4",
    "drop": "648",
    "feature": "cairn/shelter",
    "observations": "",
    "survey": "Abney level",
    "revision": "2021-07-11",
    "comments": "col height measured with Leica RX1250",
    "map50": "51 52",
    "map25": "OL47W 368W 379W",
    "xcoord": "277324",
    "ycoord": "730857",
    "latitude": "56.453851",
    "longitude": "-3.992057",
    "country": "S",
    "climbed": "",
    "tumponly": "0",
    "Ma": "1",
    "MaE": "0",
    "Hu": "1",
    "HuE": "0",
    "Tu": "1",
    "Sim": "1",
    "V5": "0",
    "M": "1",
    "MT": "0",
    "F": "0",
    "C": "0",
    "G": "0",
    "D": "0",
    "DT": "0",
    "Hew": "0",
    "N": "0",
    "Dew": "0",
    "DDew": "0",
    "HF": "0",
    "V4": "0",
    "V3": "0",
    "V2": "0",
    "V1": "0",
    "V0": "0",
    "W": "0",
    "WO": "0",
    "B": "0",
    "Sy": "0",
    "Fel": "0",
    "CoH": "0",
    "CoA": "0",
    "CoU": "0",
    "CoL": "0",
    "SIB": "0",
    "sMa": "0",
    "sHu": "0",
    "sSim": "0",
    "s5": "0",
    "s4": "0",
    "Mur": "1",
    "CT": "0",
    "GT": "0",
    "DN": "0",
    "BL": "0",
    "Bg": "0",
    "Y": "1",
    "Cm": "0",
    "T100": "0",
    "xMT": "0",
    "xC": "0",
    "xG": "0",
    "xN": "0",
    "xDT": "0",
    "O": "0",
    "Un": "0",
    "P600": "1",
    "P500": "1",
    "id": "643f0095ab5591a12a3a8c4b",
    "summary": "string",
    "images": ["string"],
    "weather": {"key": "string"},
}


fake_munros_list = {
    "munros": [
        {
            "hillnumber": "1",
            "hillname": "Ben Chonzie",
            "region": "01A",
            "parent": "",
            "classification": "Ma,M,Sim",
            "metres": "931",
            "feet": "3054",
            "gridref": "NN773308",
            "gridref10": "NN 77326 30850",
            "colgridref": "NN 5609 2772",
            "colheight": "283.4",
            "drop": "648",
            "feature": "cairn/shelter",
            "observations": "",
            "survey": "Abney level",
            "revision": "2021-07-11",
            "comments": "col height measured with Leica RX1250",
            "map50": "51 52",
            "map25": "OL47W 368W 379W",
            "xcoord": "277324",
            "ycoord": "730857",
            "latitude": "56.453851",
            "longitude": "-3.992057",
            "country": "S",
            "climbed": "",
            "tumponly": "0",
            "Ma": "1",
            "MaE": "0",
            "Hu": "1",
            "HuE": "0",
            "Tu": "1",
            "Sim": "1",
            "V5": "0",
            "M": "1",
            "MT": "0",
            "F": "0",
            "C": "0",
            "G": "0",
            "D": "0",
            "DT": "0",
            "Hew": "0",
            "N": "0",
            "Dew": "0",
            "DDew": "0",
            "HF": "0",
            "V4": "0",
            "V3": "0",
            "V2": "0",
            "V1": "0",
            "V0": "0",
            "W": "0",
            "WO": "0",
            "B": "0",
            "Sy": "0",
            "Fel": "0",
            "CoH": "0",
            "CoA": "0",
            "CoU": "0",
            "CoL": "0",
            "SIB": "0",
            "sMa": "0",
            "sHu": "0",
            "sSim": "0",
            "s5": "0",
            "s4": "0",
            "Mur": "1",
            "CT": "0",
            "GT": "0",
            "DN": "0",
            "BL": "0",
            "Bg": "0",
            "Y": "1",
            "Cm": "0",
            "T100": "0",
            "xMT": "0",
            "xC": "0",
            "xG": "0",
            "xN": "0",
            "xDT": "0",
            "O": "0",
            "Un": "0",
            "P600": "1",
            "P500": "1",
            "id": "643f0095ab5591a12a3a8c4b",
        }
    ]
}

fake_climbs = {
    "datetime": "2023-04-27T20:58:18.046000+00:00",
    "duration": "string",
    "difficulty": 0,
    "weather": "string",
    "notes": "string",
    "image": "string",
    "account_id": "string",
    "munro_id": "string",
    "id": "string",
}
